//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KovatsNorbertBeadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absents
    {
        public int Absent_ID { get; set; }
        public int Student_Absent_ID { get; set; }
        public int Hours { get; set; }
        public System.DateTime Absent_Date { get; set; }
    }
}
