//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KovatsNorbertBeadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public int Department_ID { get; set; }
        public int Department_Class_ID { get; set; }
        public int Department_Teacher_ID { get; set; }
        public string Department_Name { get; set; }
    }
}
