//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KovatsNorbertBeadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int Mark_ID { get; set; }
        public int Student_Mark_ID { get; set; }
        public int Course_ID { get; set; }
        public int Mark { get; set; }
        public System.DateTime Mark_Date { get; set; }
    }
}
