//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KovatsNorbertBeadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parents
    {
        public int Parent_ID { get; set; }
        public string Name { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Parent_Phone_Number { get; set; }
        public string Parent_Email { get; set; }
        public byte[] Parent_Student_ID { get; set; }
    }
}
