//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KovatsNorbertBeadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Student_ID { get; set; }
        public string Student_Name { get; set; }
        public string Student_First_Name { get; set; }
        public string Student_Last_Name { get; set; }
        public long Student_OM_ID { get; set; }
        public string Address { get; set; }
        public string Student_Phone_Number { get; set; }
        public string Student_Email { get; set; }
        public int Student_User_ID { get; set; }
        public int Departments_ID { get; set; }
    }
}
