//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KovatsNorbertBeadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDC
    {
        public int TDC_Teacher_ID { get; set; }
        public int TDC_Department_ID { get; set; }
        public int TDC_Course_ID { get; set; }
    }
}
