//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KovatsNorbertBeadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public int Teacher_ID { get; set; }
        public string Teacher_Name { get; set; }
        public string Teacher_First_name { get; set; }
        public string Teacher_Last_Name { get; set; }
        public string Teacher_Address { get; set; }
        public string Teacher_Phone_Number { get; set; }
        public string Teacher_Email { get; set; }
        public int Teacher_User_id { get; set; }
    }
}
