//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KovatsNorbertBeadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {

        public Users(Users user)
        {
            User_ID = user.User_ID;
            User_Name = user.User_Name;
            Password = user.Password;
            User_Access_Rank = user.User_Access_Rank;
        }
        public Users()
        {

        }

        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public int User_Access_Rank { get; set; }
    }
}
